#TODO: Provide instructions for modpack devs.
---
ModPackConfigName: null
ModPackConfigVersion: 0
ShowOTGWorldCreationMenu: true
version: 1
WorldName: "world"
Overworld:
  PresetName: "Biome Bundle"
  DimensionId: 0
  ShowInWorldCreationGUI: true
  LowestSupportedModPackConfigVersion: 0
  RemoveOnUpdate: false
  Seed: "1234565"
  GameType: "Creative"
  BonusChest: false
  AllowCheats: true
  WorldBorderRadiusInChunks: 10000
  PregeneratorRadiusInChunks: 0
  Settings:
    DimensionPortalMaterials:
    - "DIRT"
    PortalColor: "default"
    PortalParticleType: "portal"
    PortalMobType: "zombie_pigman"
    PortalMobSpawnChance: 2000
    IsOTGPlus: false
    DimensionBelow: ""
    DimensionAbove: ""
    DimensionBelowHeight: 0
    DimensionAboveHeight: 256
    TeleportToSpawnOnly: false
    WelcomeMessage: ""
    DepartMessage: ""
    HasSkyLight: true
    IsSurfaceWorld: true
    CanRespawnHere: true
    DoesWaterVaporize: false
    DoesXZShowFog: false
    UseCustomFogColor: false
    FogColorRed: 0.20000000298023224
    FogColorGreen: 0.029999999329447746
    FogColorBlue: 0.029999999329447746
    IsSkyColored: true
    CloudHeight: 128
    CanDoLightning: true
    CanDoRainSnowIce: true
    IsNightWorld: false
    VoidFogYFactor: 0.03125
    GravityFactor: 0.08
    ShouldMapSpin: false
    CanDropChunk: true
    RespawnDimension: 0
    MovementFactor: 1
    ItemsToAddOnJoinDimension: ""
    ItemsToRemoveOnJoinDimension: ""
    ItemsToAddOnLeaveDimension: ""
    ItemsToRemoveOnLeaveDimension: ""
    ItemsToAddOnRespawn: ""
    SpawnPointSet: true
    SpawnPointX: -284
    SpawnPointY: 110
    SpawnPointZ: 1024
    PlayersCanBreakBlocks: true
    ExplosionsCanBreakBlocks: true
    PlayersCanPlaceBlocks: true
  GameRules:
    CommandBlockOutput: true
    DisableElytraMovementCheck: false
    DoDaylightCycle: true
    DoEntityDrops: true
    DoFireTick: true
    DoLimitedCrafting: false
    DoMobLoot: true
    DoMobSpawning: true
    DoTileDrops: true
    DoWeatherCycle: true
    GameLoopFunction: true
    KeepInventory: false
    LogAdminCommands: true
    MaxCommandChainLength: 65536
    MaxEntityCramming: 24
    MobGriefing: true
    NaturalRegeneration: true
    RandomTickSpeed: 3
    ReducedDebugInfo: false
    SendCommandFeedback: true
    ShowDeathMessages: true
    SpawnRadius: 10
    SpectatorsGenerateChunks: true
Dimensions: []